const obj = [
  {
    name: 'massage',
    thumbnail: 'massage.jpg',
    description: 'massage',
    price: 500,
    image: 'https',
  },
  {
    name: 'spa',
    thumbnail: 'spa.jpg',
    description: 'spa',
    price: 400,
    image: 'https',
  },
  {
    name: 'restaurant',
    thumbnail: 'restaurant.jpg',
    description: 'restaurant',
    price: 700,
    image: 'https',
  },
  {
    name: 'swimming pool',
    thumbnail: 'swimming-pool.jpg',
    description: 'swimming pool',
    price: 300,
    image: 'https',
  },
  {
    name: 'karaoke',
    thumbnail: 'karaoke.jpg',
    description: 'karaoke',
    price: 350,
    image: 'https',
  },
  {
    name: "Car rental services",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Catering services",
    price: 200,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Concierge services",
    price: 300,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Courier services",
    price: 400,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Doctor on call",
    price: 600,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Dry cleaning",
    price: 800,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Excursions and guided tours",
    price: 1000,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Flower arrangement",
    price: 1200,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Ironing service",
    price: 1300,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Laundry and valet service",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Mail services",
    price: 500,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Room service (24-hour)",
    price: 700,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Shoeshine service",
    price: 2000,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Ticket service",
    price: 400,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Transfer and chauffeur driven limousine services",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Turndown service",
    price: 300,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Valet parking",
    price: 1000,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Wake-up call",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Wedding services",
    price: 1000,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Wheelchair accessible",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Wi-Fi in public areas",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Airport transfer",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Babysitting",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Bar",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Bicycle rental",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Business center",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Car park",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Coffee shop",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Concierge",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Currency exchange",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Elevator",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Facilities for disabled guests",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Family room",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Laundry service",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Luggage storage",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Meeting facilities",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Restaurant",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Room service",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Safety deposit boxes",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Salon",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Shops",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Smoking area",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Tours",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "Wi-Fi in public areas",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "24-hour front desk",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  },
  {
    name: "24-hour room service",
    price: 100,
    thumbnail: 'service.jpg',
    description: 'service description',
    image: 'https',
  }
]
const urls = [
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image01_v6902g',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image02_i6zmui',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image00_cf6bnv',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image07_cmgbjw',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image05_wunmvy',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image06_zwmn04',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image14_ij0zwz',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image04_rexrcu',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image03_flqcna',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image12_ifuft4',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image11_ed1bvz',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image10_meauw7',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image09_wiz3r7',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image23_uo3ies',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image08_h1jvuk',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image20_zysi9x',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image19_r4wyac',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image18_bogxlz',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image17_ezl3cj',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image16_xaipa0',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image15_pkrybn',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image26_oesenr',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image13_tpfjy2',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image25_iakr3s',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image24_cbevd9',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image46_mbhdik',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image21_qggj5f',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image22_jfzhgr',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image33_psyptx',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image32_od2adi',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image52_zvzc1t',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image31_bsbzzz',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image30_rwlcup',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image29_nbvbf0',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image28_w5tmvz',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image27_gdifyw',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image39_fyjxnw',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image38_pdq7lx',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image37_oo1yqx',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image36_puscbf',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image45_tnwqon',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image35_mekkvx',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image34_kemjki',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image44_ba0fp9',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image43_iirw8p',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image40_hzivi1',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image42_ufhtmh',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image41_gypn1i',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image51_ri5khk',
  'http://res.cloudinary.com/dmr3ppomm/image/upload/v1/hotel_service/image47_zjys6j'
]

const testSeed = () => {
  for (let i = 0; i < obj.length; i += 1) {
    obj[i].image = urls[i];
    console.log(obj[i]);
  }
}

module.exports = testSeed;
